name: Bestiary
version: '@version@'
main: me.jeremiah.bestiary.BestiaryPlugin
loader: me.jeremiah.bestiary.BestiaryLoader
api-version: '1.21'
load: STARTUP
authors: [ ImNotStable ]
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
      join-classpath: true